### PR TITLE
Add opt-in persistent overriding for transient tile data

### PR DESCRIPTION
**Pull request by datakurre**
This is required for new WIP static content layout support in p.a.blocks and p.a.mosaic. In brief, enabling to be able to use static centrally managed layouts, but still be able override individual tile configurations using context specific persistent annotations.

Note: It's up to users to not abuse this. Overriding a few tiles is OK. Overriding a long front page with dozens of tiles is not (performance wise).

### CODE REVIEW

**Comment by datakurre** [comment]
@vangheem Restored the X-Persistent-Tile query parant support. It seems I did not sleep well enough to think properly today :)

**Comment by datakurre** [comment]
@vangheem An now, finally, X-Tile-Persistent as query parameter is the only option, because it's the only way this could work with ESI. Also added some code with tests into p.a.blocks to inject query parameters into contentLayout tiles in https://github.com/plone/plone.app.blocks/commit/8545205314114d85db1e2875e26d44e85194848f

**Comment by vangheem** [comment]
Alright, I'm not sure I like that more than IPersistentTileOverrides or the request environ variable. Maybe there is no perfect way. Just too bad we're parsing that contentLayout DOM twice.

**Comment by datakurre** [comment]
@vangheem An alternative would be to *always* check if a persistent tile is available (as in my original draft) and use it instead of transient data. Marker interface would not work for ESI requests.

How would you like about ramcaching postfixed contentLayouts against hash from their original contents? That should work pretty well in this case.

**Comment by vangheem** [comment]
I can't remember the scenario right now and I should have documented it but
there was a case where your original code didn't cover correctly I think so
I had to go with the current approach. So just be careful. We'll have to
try and have decent robot tests for everything...

**Comment by datakurre** [comment]
@vangheem Did you recall the issue with my initial proposal (always using persistent data if such exist to require X-Tile-Persistent only when overriding transient data at first time)?

**Comment by vangheem** [comment]
Yes, it doesn't always work. If you don't clear the persistent data properly switching between custom layout and non-custom layout can give wonky results on rendered page. It's best to be explicit it seems.

**Comment by datakurre** [comment]
Thanks. I get that now. Then we just need to cache the postfixed layout in p.a.blocks to minimize extra xml parsing.

**Pull request merged**
